name: ml_project
channels:
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - pyarrow
  - scikit-learn
  - matplotlib
  - jupyter
  - seaborn

prefix: /Users/kevinhu/Programming/ml_project/ML_project2025/.conda
